export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_REQUEST_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_FAILED_SHIPPING = "CART_SAVE_SHIPPING";

export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_ERROR = "CART_LIST_ERROR";
