export const ENTERPRISE_LIST_REQUEST = "ENTERPRISE_LIST_REQUEST";
export const ENTERPRISE_LIST_SUCCESS = "ENTERPRISE_LIST_SUCCESS";
export const ENTERPRISE_LIST_ERROR = "ENTERPRISE_LIST_ERROR";

export const ENTERPRISE_UPDATE_REQUEST = "ENTERPRISE_UPDATE_REQUEST";
export const ENTERPRISE_UPDATE_SUCCESS = "ENTERPRISE_UPDATE_SUCCESS";
export const ENTERPRISE_UPDATE_ERROR = "ENTERPRISE_UPDATE_ERROR";

export const ENTERPRISE_ADD_REQUEST = "ENTERPRISE_ADD_REQUEST";
export const ENTERPRISE_ADD_SUCCESS = "ENTERPRISE_ADD_SUCCESS";
export const ENTERPRISE_ADD_ERROR = "ENTERPRISE_ADD_ERROR";

export const ENTERPRISE_DELETE_REQUEST = "ENTERPRISE_DELETE_REQUEST";
export const ENTERPRISE_DELETE_SUCCESS = "ENTERPRISE_DELETE_SUCCESS";
export const ENTERPRISE_DELETE_ERROR = "ENTERPRISE_DELETE_ERROR";
