// customer constants
export const PLACEORDER_SAVE_REQUEST = "PLACEORDER_SAVE_REQUEST";
export const PLACEORDER_SAVE_SUCCESS = "PLACEORDER_SAVE_SUCCESS";
export const PLACEORDER_SAVE_ERROR = "PLACEORDER_SAVE_ERROR";

export const ORDERSUMMARY_LIST_REQUEST = "ORDERSUMMARY_LIST_REQUEST";
export const ORDERSUMMARY_LIST_SUCCESS = "ORDERSUMMARY_LIST_SUCCESS";
export const ORDERSUMMARY_LIST_ERROR = "ORDERSUMMARY_LIST_ERROR";

export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
export const ORDER_CANCEL_ERROR = "ORDER_CANCEL_ERROR";

// /////////////////////////////////////////////////////////////////////////////////////
// seller constants

// Constants for pending order list
export const PENDINGORDER_LIST_REQUEST = "PENDINGORDER_LIST_REQUEST";
export const PENDINGORDER_LIST_SUCCESS = "PENDINGORDER_LIST_SUCCESS";
export const PENDINGORDER_LIST_ERROR = "PENDINGORDER_LIST_ERROR";
export const PENDINGORDER_LIST_CLEAR = "PENDINGORDER_LIST_CLEAR";

// Constants for  ongoing list
export const ONGOING_LIST_REQUEST = "ONGOING_LIST_REQUEST";
export const ONGOING_LIST_SUCCESS = "ONGOING_LIST_SUCCESS";
export const ONGOING_LIST_ERROR = "ONGOING_LIST_ERROR";
export const ONGOING_LIST_CLEAR = "ONGOING_LIST_CLEAR";

// Constants for completed list
export const COMPLETED_LIST_REQUEST = "COMPLETED_LIST_REQUEST";
export const COMPLETED_LIST_SUCCESS = "COMPLETED_LIST_SUCCESS";
export const COMPLETED_LIST_ERROR = "COMPLETED_LIST_ERROR";
export const COMPLETED_LIST_CLEAR = "COMPLETED_LIST_CLEAR";

// Constants for canceleld list
export const CANCELLED_LIST_REQUEST = "CANCELLED_LIST_REQUEST";
export const CANCELLED_LIST_SUCCESS = "CANCELLED_LIST_SUCCESS";
export const CANCELLED_LIST_ERROR = "CANCELLED_LIST_ERROR";
export const CANCELLED_LIST_CLEAR = "CANCELLED_LIST_CLEAR";

// Constants for Accepting pending orders
export const ORDER_ACCEPT_REQUEST = "ORDER_ACCEPT_REQUEST";
export const ORDER_ACCEPT_SUCCESS = "ORDER_ACCEPT_SUCCESS";
export const ORDER_ACCEPT_ERROR = "ORDER_ACCEPT_ERROR";

// constants for completing ongoing orders
export const ORDER_COMPLETE_REQUEST = "ORDER_COMPLETE_REQUEST";
export const ORDER_COMPLETE_SUCCESS = "ORDER_COMPLETE_SUCCESS";
export const ORDER_COMPLETE_ERROR = "ORDER_COMPLETE_ERROR";
