export const SHIPPING_SAVE_ITEMS = "SHIPPING_SAVE_ITEMS";
export const SHIPPING_REQUEST_ITEMS = "SHIPPING_REQUEST_ITEMS";
export const SHIPPING_FAILED_ITEMS = "SHIPPING_FAILED_ITEMS";

export const SHIPPING_SAVE_PLACEORDER = "SHIPPING_REQUEST_PLACEORDER";
export const SHIPPING_REQUEST_PLACEORDER = "SHIPPING_SAVE_PLACEORDER";
export const SHIPPING_FAILED_PLACEORDER = "SHIPPING_FAILED_PLACEORDER";
